# Schema for the configuration files of the group module.

group.settings:
  type: 'config_object'
  label: 'Group settings'
  mapping:
    use_admin_theme:
      type: 'boolean'
      label: 'Use admin theme when editing or creating groups'

group.type.*:
  type: 'config_entity'
  label: 'Group type'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    description:
      type: 'text'
      label: 'Description'
    roles:
      type: 'sequence'
      label: 'Group role IDs'
      sequence:
        type: 'string'
        label: 'Group role ID'
    content:
      type: 'sequence'
      label: 'Group content enabler plugins'
      sequence:
        type: 'mapping'
        label: 'Group content plugin configuration'
        mapping:
          id:
            type: 'string'
            label: 'Plugin ID'
          data:
            type: 'sequence'
            label: 'Plugin configuration'

group.role.*:
  type: 'config_entity'
  label: 'Group role'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    internal:
      type: 'boolean'
      label: 'Group role is directly tied to a group type'
    weight:
      type: 'integer'
      label: 'Weight'
    permissions:
      type: 'sequence'
      label: 'Permissions'
      sequence:
        type: 'string'
        label: 'Group permission'


group_content_type:
  type: 'config_entity'
  label: 'Group content type'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    description:
      type: 'text'
      label: 'Description'
    group_type:
      type: 'text'
      label: 'Group type ID'
    content_plugin:
      type: 'text'
      label: 'Group content plugin ID'

# Follows the pattern group.content_type.GROUP_TYPE_ID.PLUGIN_ID.
group.content_type.*.*:
  type: 'group_content_type'
  label: 'Group content type'

# Follows the pattern group.content_type.GROUP_TYPE_ID.PLUGIN_ID.DERIVATIVE_ID.
group.content_type.*.*.*:
  type: 'group_content_type'
  label: 'Group content type (derivative)'
