# Schema for the configuration files of the group module.

group.settings:
  type: config_object
  label: 'Group settings'
  mapping:
    use_admin_theme:
      type: boolean
      label: 'Use admin theme when editing or creating groups'

group.type.*:
  type: config_entity
  label: 'Group type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
