# Schema for the configuration files of the group module.

group.settings:
  type: 'config_object'
  label: 'Group settings'
  mapping:
    use_admin_theme:
      type: 'boolean'
      label: 'Use admin theme when editing or creating groups'

group.type.*:
  type: 'config_entity'
  label: 'Group type'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    description:
      type: 'text'
      label: 'Description'
    roles:
      type: 'sequence'
      label: 'Group role ids'
      sequence:
        type: 'string'
        label: 'Group role id'

group.role.*:
  type: 'config_entity'
  label: 'Group role'
  mapping:
    id:
      type: 'string'
      label: 'Machine-readable name'
    label:
      type: 'label'
      label: 'Label'
    internal:
      type: 'boolean'
      label: 'Group role is directly tied to a group type'
    weight:
      type: 'integer'
      label: 'Weight'
    permissions:
      type: 'sequence'
      label: 'Permissions'
      sequence:
        type: 'string'
        label: 'Group permission'
